# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\rnexus.product\"!\n\x12GetProductsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"?\n\x13GetProductsResponse\x12(\n\x08products\x18\x01 \x03(\x0b\x32\x16.nexus.product.Product\"E\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t2f\n\x0eProductService\x12T\n\x0bGetProducts\x12!.nexus.product.GetProductsRequest\x1a\".nexus.product.GetProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTSREQUEST']._serialized_start=32
  _globals['_GETPRODUCTSREQUEST']._serialized_end=65
  _globals['_GETPRODUCTSRESPONSE']._serialized_start=67
  _globals['_GETPRODUCTSRESPONSE']._serialized_end=130
  _globals['_PRODUCT']._serialized_start=132
  _globals['_PRODUCT']._serialized_end=201
  _globals['_PRODUCTSERVICE']._serialized_start=203
  _globals['_PRODUCTSERVICE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
