# Generated by Django 4.2.11 on 2026-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
    ]
