# Generated by Django 4.2.11 on 2026-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default_billing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default_shipping',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
