# Generated by Django 4.2.11 on 2026-06-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_snapshot',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
    ]
