# Generated by Django 4.2.11 on 2026-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_resource_id_uploadedfile_resource_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['resource_type', 'resource_id'], name='files_uploa_resourc_82f34a_idx'),
        ),
    ]
