# Generated by Django 4.2.11 on 2026-05-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
